language: python
python:
  - "2.7"

services: postgresql

env:
  - DATABASE_URL=postgres://postgres@localhost/travis_ci_test

install:
  - make pip

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py migrate

script:
  - make validate

branches:
  only:
    - master
    - dev
