# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spend_ya_money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamoney',
            name='account',
            field=models.TextField(default=datetime.datetime(2016, 2, 28, 15, 41, 23, 901573, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
