# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spend_ya_money', '0002_yamoney_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(unique=True)),
                ('username', models.TextField()),
                ('expenditure', models.ManyToManyField(to='spend_ya_telegram.Expenditure')),
                ('wallet', models.ManyToManyField(to='spend_ya_money.YaMoney')),
            ],
        ),
    ]
