# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend_ya_telegram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expenditure',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='Expenditure',
        ),
    ]
